### ISSUE TITLE
About to send template to Sam

### ISSUE THREAD

**Issue by bbblitz** [alexa6425/InteractiveBook#1]
Hey everyone, I've changed the template slightly, I'm about to send it off to Professor Hamilton (I'll be sending it at 11:30 pm today) I thought I'd open an issue (so everyone gets an email) to invite comments so you can stop me in time if you think something's wrong.

**Comment by brp76** [comment]
I think we decided the navigation bar should be at the top of the page for consistency

**Comment by bbblitz** [comment]
We did???
Workingonit

**Comment by bbblitz** [comment]
fixed in 17b2b1533fab88eb58e75b4db88b1ec11d3b0629

**Comment by bbblitz** [comment]
Alright, sent. Anything we want to change now will have to be done in javascript or the css
